title: "Effective Docker"
summary: "Dockerの初期設定，docker compose，imageを小さくするベストプラクティス，リモート，ローカルキャッシュを使う，Dev Containerなどについて詳しく解説"
topics: ["docker", "dockercompose", "devcontainer"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - hello
  - docker_term
  - docker_setup
  - docker-compose
  - docker_image
  - docker_layer
  - docker_build_cache
  - docker_remotecache
  - docker-security
  - docker_network
  - docker_volume
  - docker_tips

